name: Build and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purescript-contrib/setup-purescript@main
        with:
          spago: unstable
          purescript: "0.15.13"
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm install -g spago@next
      - run: spago build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purescript-contrib/setup-purescript@main
        with:
          spago: unstable
          purescript: "0.15.13"
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm install -g spago@next
      - run: spago test
