name: Build and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purescript-contrib/setup-purescript@main
        with:
          spago: unstable
          purescript: "0.15.13"
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm install -g spago@next
      - run: spago build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purescript-contrib/setup-purescript@main
        with:
          spago: unstable
          purescript: "0.15.13"
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: crazy-max/ghaction-setup-docker@v3.0.0
        with:
          version: v24.0.5
      - uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.23.1
      - run: docker --version
      - run: docker-compose--version
      - run: npm install
      - run: npm install -g spago@next
      - run: spago test
